const countries = {
  PS: {
    display: "فلسطين",
    api: "PS",
    cities: [
      { display: "غزة", api: "gaza" },
      { display: "القدس", api: "quds" },
      { display: "رام الله", api: "ramallah" },
      { display: "الخليل", api: "hebron" },
      { display: "نابلس", api: "nablus" },
      { display: "جنين", api: "jenin" },
      { display: "طولكرم", api: "tulkarm" },
      { display: "قلقيلية", api: "qalqilya" },
      { display: "بيت لحم", api: "bethlehem" },
      { display: "سلفيت", api: "salfit" },
      { display: "طوباس", api: "tubas" },
      { display: "أريحا", api: "jericho" },
      { dsipla: "خان يونس", api: "khan-younis" },
      { display: "رفح", api: "rafah" },
    ],
  },
  JO: {
    display: "الأردن",
    api: "JO",
    cities: [
      { display: "عمّان", api: "amman" },
      { display: "إربد", api: "irbid" },
      { display: "الزرقاء", api: "zarqa" },
      { display: "العقبة", api: "aqaba" },
      { display: "السلط", api: "salt" },
      { display: "معان", api: "maan" },
      { display: "الرمثا", api: "ramtha" },
      { display: "الطفيلة", api: "tafila" },
      { display: "مادبا", api: "madaba" },
      { display: "الكرك", api: "karak" },
      { display: "المفرق", api: "mafraq" },
      { display: "جرش", api: "jerash" },
      { display: "عجلون", api: "ajloun" },
      { display: "البلقاء", api: "balqa" },
    ],
  },
  SA: {
    display: "السعودية",
    api: "SA",
    cities: [
      { display: "الرياض", api: "riyadh" },
      { display: "مكة", api: "makkah" },
      { display: "المدينة", api: "madina" },
      { display: "نجران", api: "najran" },
      { display: "الباحة", api: "al-baha" },
      { display: "تبوك", api: "tabuk" },
      { display: "حائل", api: "hail" },
      { display: "أبها", api: "abha" },
      { display: "جازان", api: "jazan" },
      { dispay: "الدمام", api: "dammam" },
      { dispaly: "بريدة", api: "buraydah" },
      { display: "عرعر", api: "arar" },
      { display: "سكاكا", api: "sakaka" },
    ],
  },
  EG: {
    display: "مصر",
    api: "EG",
    cities: [
      { display: "القاهرة", api: "cairo" },
      { display: "الإسكندرية", api: "alexandria" },
      { display: "الجيزة", api: "giza" },
      { display: "المنصورة", api: "mansoura" },
      { display: "بورسعيد", api: "port-said" },
      { display: "الفيوم", api: "fayoum" },
      { display: "الزقازيق", api: "zagazig" },
      { display: "الإسماعيلية", api: "ismailia" },
      { display: "المنيا", api: "minya" },
      { display: "أسيوط", api: "asyut" },
      { display: "سوهاج", api: "sohag" },
      { display: "قنا", api: "qena" },
      { display: "الغردقة", api: "hurghada" },
      { display: "دمياط", api: "damietta" },
      { display: "العريش", api: "arish" },
      { display: "العاشر من رمضان", api: "10th-of-ramadan" },
      { display: "بنها", api: "banha" },
      { display: "بني سويف", api: "beni-suef" },
      { display: "دمنهور", api: "damanhur" },
      { display: "المحلة الكبرى", api: "mahalla" },
      { display: "المنوفية", api: "menouf" },
      { display: "السويس", api: "suez" },
      { display: "شبين الكوم", api: "shibin-al-kom" },
      { display: "طنطا", api: "tanta" },
      { display: "كفر الشيخ", api: "kafr-el-sheikh" },
      { display: "مرسى مطروح", api: "marsa-matruh" },
      { display: "الوادي الجديد", api: "new-valley" },
      { display: "قليوب", api: "qalyub" },
      { display: "سوهاج", api: "sohag" },
      { display: "البحيرة", api: "beheira" },
      { display: "الدقهلية", api: "daqahlia" },
      { display: "الشرقية", api: "sharqia" },
      { display: "الغربية", api: "gharbia" },
      { display: "الفيوم", api: "fayoum" },
      { display: "القليوبية", api: "qalyubia" },
      { display: "المنوفية", api: "menoufia" },
      { display: "الوادي الجديد", api: "new-valley" },
      { display: "البحيرة", api: "beheira" },
      { display: "الدقهلية", api: "daqahlia" },
      { display: "الشرقية", api: "sharqia" },
      { display: "الغربية", api: "gharbia" },
      { display: "الأقصر", api: "luxor" },
      { display: "أسوان", api: "aswan" },
      { display: "البحر الأحمر", api: "red-sea" },
      { display: "الوادي الجديد", api: "new-valley" },
      { display: "البحيرة", api: "beheira" },
      { display: "الدقهلية", api: "daqahlia" },
      { display: "الشرقية", api: "sharqia" },
      { display: "الغربية", api: "gharbia" },
      { display: "الأقصر", api: "luxor" },
      { display: "أسوان", api: "aswan" },
      { display: "البحر الأحمر", api: "red-sea" },
    ],
  },
  KW: {
    display: "الكويت",
    api: "KW",
    cities: [
      { display: "الكويت", api: "kuwait" },
      { display: "الأحمدي", api: "ahmadi" },
      { display: "حولي", api: "hawalli" },
      { display: "الفروانية", api: "farwaniya" },
      { display: "مبارك الكبير", api: "mubarak-al-kabeer" },
      { display: "الجهراء", api: "jahra" },
    ],
  },
  AE: {
    display: "الإمارات",
    api: "AE",
    cities: [
      { display: "دبي", api: "dubai" },
      { display: "أبوظبي", api: "abu-dhabi" },
      { display: "الشارقة", api: "sharjah" },
      { display: "عجمان", api: "ajman" },
      { display: "أم القيوين", api: "um-al-quwain" },
      { display: "رأس الخيمة", api: "ras-al-khaimah" },
      { display: "الفجيرة", api: "fujairah" },
    ],
  },
  BH: {
    display: "البحرين",
    api: "BH",
    cities: [
      { display: "المنامة", api: "manama" },
      { display: "المحرق", api: "muharraq" },
      { display: "الرفاع", api: "riffa" },
      { display: "حمد", api: "hamad" },
      { display: "عالي", api: "ala" },
      { display: "المحرق", api: "muharraq" },
      { display: "الرفاع", api: "riffa" },
      { display: "حمد", api: "hamad" },
      { display: "عالي", api: "ala" },
    ],
  },
  OM: {
    display: "عمان",
    api: "OM",
    cities: [
      { display: "مسقط", api: "muscat" },
      { display: "صلالة", api: "salalah" },
      { display: "صحار", api: "sohar" },
      { display: "نزوى", api: "nizwa" },
      { display: "بركاء", api: "barka" },
      { display: "البريمي", api: "ibra" },
      { display: "الخابورة", api: "khaborah" },
      { display: "السويق", api: "suwayq" },
      { display: "صحم", api: "saham" },
      { display: "العامرات", api: "al-amerat" },
      { display: "الخابورة", api: "khaborah" },
      { display: "السويق", api: "suwayq" },
      { display: "صحم", api: "saham" },
      { display: "العامرات", api: "al-amerat" },
    ],
  },
  QA: {
    display: "قطر",
    api: "QA",
    cities: [
      { display: "الدوحة", api: "doha" },
      { display: "الريان", api: "ar-rayyan" },
      { display: "الوكرة", api: "al-wakrah" },
      { display: "الخور", api: "al-khor" },
      { display: "أم صلال", api: "umm-salal" },
      { display: "الشمال", api: "ash-shamal" },
    ],
  },
  YE: {
    display: "اليمن",
    api: "YE",
    cities: [
      { display: "صنعاء", api: "sanaa" },
      { display: "عدن", api: "aden" },
      { display: "تعز", api: "taizz" },
      { display: "الحديدة", api: "al-hudaydah" },
      { display: "إب", api: "ibb" },
      { display: "المكلا", api: "mukalla" },
      { display: "ذمار", api: "dhamar" },
      { display: "البيضاء", api: "al-bayda" },
      { display: "سيئون", api: "sayun" },
      { display: "الغيضة", api: "al-ghaydah" },
      { display: "رداع", api: "radad" },
      { display: "المخا", api: "makha" },
      { display: "الحديدة", api: "al-hudaydah" },
      { display: "إب", api: "ibb" },
      { display: "المكلا", api: "mukalla" },
      { display: "ذمار", api: "dhamar" },
      { display: "البيضاء", api: "al-bayda" },
      { display: "سيئون", api: "sayun" },
      { display: "الغيضة", api: "al-ghaydah" },
      { display: "رداع", api: "radad" },
      { display: "المخا", api: "makha" },
    ],
  },
  SY: {
    display: "سوريا",
    api: "SY",
    cities: [
      { display: "دمشق", api: "damascus" },
      { display: "حلب", api: "aleppo" },
      { display: "حمص", api: "homs" },
      { display: "حماة", api: "hamah" },
      { display: "اللاذقية", api: "latakia" },
      { display: "دير الزور", api: "deir-ez-zor" },
      { display: "الرقة", api: "ar-raqqa" },
      { display: "ادلب", api: "idlib" },
      { display: "السويداء", api: "as-suwayda" },
      { display: "درعا", api: "daraa" },
      { display: "القنيطرة", api: "al-qunaytirah" },
      { display: "الحسكة", api: "al-hasakah" },
      { display: "طرطوس", api: "tartus" },
      { display: "القنيطرة", api: "al-qunaytirah" },
      { display: "الحسكة", api: "al-hasakah" },
      { display: "طرطوس", api: "tartus" },
    ],
  },
  IQ: {
    display: "العراق",
    api: "IQ",
    cities: [
      { display: "بغداد", api: "baghdad" },
      { display: "البصرة", api: "basra" },
      { display: "الموصل", api: "mosul" },
      { display: "كركوك", api: "kirkuk" },
      { display: "النجف", api: "an-najaf" },
      { display: "الديوانية", api: "ad-diwaniyah" },
      { display: "السليمانية", api: "sulaymaniyah" },
      { display: "كربلاء", api: "karbala" },
      { display: "العمارة", api: "al-amara" },
      { display: "البصرة", api: "basra" },
      { display: "الموصل", api: "mosul" },
      { display: "كركوك", api: "kirkuk" },
      { display: "النجف", api: "an-najaf" },
      { display: "الديوانية", api: "ad-diwaniyah" },
      { display: "السليمانية", api: "sulaymaniyah" },
      { display: "كربلاء", api: "karbala" },
      { display: "العمارة", api: "al-amara" },
    ],
  },
  LB: {
    display: "لبنان",
    api: "LB",
    cities: [
      { display: "بيروت", api: "beirut" },
      { display: "طرابلس", api: "tripoli" },
      { display: "صيدا", api: "sidon" },
      { display: "زحلة", api: "zahle" },
      { display: "جبيل", api: "jbeil" },
      { display: "بعلبك", api: "baalbek" },
      { display: "النبطية", api: "nabatieh" },
      { display: "بعلبك", api: "baalbek" },
      { display: "النبطية", api: "nabatieh" },
    ],
  },
  LY: {
    display: "ليبيا",
    api: "LY",
    cities: [
      { display: "طرابلس", api: "tripoli" },
      { display: "بنغازي", api: "benghazi" },
      { display: "مصراتة", api: "misrata" },
      { display: "زوارة", api: "zawiyah" },
      { display: "سرت", api: "surt" },
      { display: "الخمس", api: "al-khums" },
      { display: "الزاوية", api: "az-zawiya" },
      { display: "درنة", api: "darnah" },
      { display: "البيضاء", api: "al-bayda" },
      { display: "غات", api: "ghat" },
      { display: "سبها", api: "sabha" },
      { display: "ترهونة", api: "tarhuna" },
      { display: "المرج", api: "al-marj" },
      { display: "الزنتان", api: "az-zintan" },
      { display: "الجميل", api: "al-jumayl" },
      { display: "القره بوللي", api: "al-qurayyah" },
      { display: "القره بوللي", api: "al-qurayyah" },
    ],
  },
  TN: {
    display: "تونس",
    api: "TN",
    cities: [
      { display: "تونس", api: "tunis" },
      { display: "صفاقس", api: "sfax" },
      { display: "سوسة", api: "sousse" },
      { display: "قفصة", api: "gafsa" },
      { display: "قابس", api: "gabes" },
      { display: "القيروان", api: "kairouan" },
      { display: "المنستير", api: "monastir" },
      { display: "جندوبة", api: "jendouba" },
      { display: "الكاف", api: "kasserine" },
      { display: "القصرين", api: "kebili" },
      { display: "سليانة", api: "siliana" },
      { display: "المهدية", api: "mahdia" },
      { display: "بنزرت", api: "bizerte" },
      { display: "نابل", api: "nabeul" },
      { display: "زغوان", api: "zaghouan" },
      { display: "تطاوين", api: "tozeur" },
      { display: "باجة", api: "beja" },
      { display: "مدنين", api: "medenine" },
      { display: "تطاوين", api: "tozeur" },
      { display: "باجة", api: "beja" },
      { display: "مدنين", api: "medenine" },
    ],
  },
  DZ: {
    display: "الجزائر",
    api: "DZ",
    cities: [
      { display: "الجزائر", api: "algiers" },
      { display: "ورقلة", api: "ouargla" },
      { display: "قسنطينة", api: "constantine" },
      { display: "ورهاوة", api: "ouargla" },
    ],
  },
  MA: {
    display: "المغرب",
    api: "MA",
    cities: [
      { display: "الرباط", api: "rabat" },
      { display: "الدار البيضاء", api: "casablanca" },
      { display: "فاس", api: "fez" },
      { display: "مراكش", api: "marrakech" },
      { display: "أكادير", api: "agadir" },
      { display: "طنجة", api: "tangier" },
      { display: "مكناس", api: "meknes" },
      { display: "أكادير", api: "agadir" },
      { display: "طنجة", api: "tangier" },
      { display: "مكناس", api: "meknes" },
    ],
  },
  ID: {
    display: "إندونيسيا",
    api: "ID",
    cities: [
      { display: "جاكرتا", api: "jakarta" },
      { display: "سورابايا", api: "surabaya" },
      { display: "ميدان", api: "medan" },
      { display: "باندونج", api: "bandung" },
      { display: "باليكبابان", api: "palembang" },
      { display: "طنجة", api: "tanger" },
      { display: "مكناس", api: "meknes" },
    ],
  },
  PK: {
    display: "باكستان",
    api: "PK",
    cities: [
      { display: "كراتشي", api: "karachi" },
      { display: "لاهور", api: "lahore" },
      { display: "فيصل آباد", api: "faisalabad" },
      { display: "روالبندي", api: "rawalpindi" },
      { display: "ملتان", api: "multan" },
      { display: "حيدرآباد", api: "hyderabad" },
      { display: "جدة", api: "jeddah" },
      { display: "مكة", api: "makkah" },
      { display: "المدينة", api: "madina" },
    ],
  },
  TR: {
    display: "تركيا",
    api: "TR",
    cities: [
      { display: "اسطنبول", api: "istanbul" },
      { display: "أنقرة", api: "ankara" },
      { display: "إزمير", api: "izmir" },
      { display: "بورصا", api: "bursa" },
      { display: "أضنة", api: "adana" },
      { display: "غازي عنتاب", api: "gaziantep" },
      { display: "كونيا", api: "konya" },
      { display: "أضنة", api: "adana" },
      { display: "غازي عنتاب", api: "gaziantep" },
      { display: "كونيا", api: "konya" },
    ],
  },
  AF: {
    display: "أفغانستان",
    api: "AF",
    cities: [
      { display: "كابول", api: "kabul" },
      { display: "كندهار", api: "kandahar" },
      { display: "مزار شريف", api: "mazar-i-sharif" },
      { display: "هرات", api: "herat" },
      { display: "بلخ", api: "balkh" },
      { display: "قندهار", api: "kandahar" },
      { display: "مزار شريف", api: "mazar-i-sharif" },
      { display: "هرات", api: "herat" },
      { display: "بلخ", api: "balkh" },
    ],
  },
  IR: {
    display: "إيران",
    api: "IR",
    cities: [
      { display: "طهران", api: "tehran" },
      { display: "مشهد", api: "mashhad" },
      { display: "اصفهان", api: "isfahan" },
      { display: "كرج", api: "karaj" },
      { display: "تبريز", api: "tabriz" },
      { display: "شيراز", api: "shiraz" },
      { display: "قم", api: "qom" },
      { display: "اهواز", api: "ahvaz" },
      { display: "كرمانشاه", api: "kermanshah" },
      { display: "اصفهان", api: "isfahan" },
      { display: "كرج", api: "karaj" },
      { display: "تبريز", api: "tabriz" },
      { display: "شيراز", api: "shiraz" },
      { display: "قم", api: "qom" },
      { display: "اهواز", api: "ahvaz" },
      { display: "كرمانشاه", api: "kermanshah" },
    ],
  },
  UZ: {
    display: "أوزبكستان",
    api: "UZ",
    cities: [
      { display: "طشقند", api: "tashkent" },
      { display: "نمنكان", api: "namangan" },
      { display: "أنديجان", api: "andijan" },
      { display: "سمرقند", api: "samarkand" },
      { display: "فرغانة", api: "fergana" },
      { display: "بوخارا", api: "bukhara" },
      { display: "نوكوس", api: "nukus" },
      { display: "قرقين", api: "qarshi" },
      { display: "نوكوس", api: "nukus" },
      { display: "قرقين", api: "qarshi" },
    ],
  },
  TM: {
    display: "تركمانستان",
    api: "TM",
    cities: [
      { display: "عشق آباد", api: "ashgabat" },
      { display: "تركمنباشي", api: "turkmenbashi" },
      { display: "داشوغوز", api: "dashoguz" },
      { display: "ماري", api: "mary" },
      { display: "بايرام علي", api: "bayramaly" },
      { display: "تركمنابات", api: "turkmenabat" },
      { display: "بلخ", api: "balkh" },
    ],
  },
  TJ: {
    display: "طاجيكستان",
    api: "TJ",
    cities: [
      { display: "دوشنبه", api: "dushanbe" },
      { display: "خجرون", api: "khorugh" },
      { display: "خجرون", api: "khorugh" },
    ],
  },
  KG: {
    display: "قرغيزستان",
    api: "KG",
    cities: [
      { display: "بشكيك", api: "bishkek" },
      { display: "أوش", api: "osh" },
      { display: "جلال-آباد", api: "jalal-abad" },
      { display: "كارا-بالت", api: "karabalta" },
      { display: "كارا-سوو", api: "karasuu" },
      { display: "كارا-بالت", api: "karabalta" },
      { display: "كارا-سوو", api: "karasuu" },
    ],
  },
  UG: {
    display: "أوغندا",
    api: "UG",
    cities: [
      { display: "كامبالا", api: "kampala" },
      { display: "جينجا", api: "jinja" },
      { display: "مبارا", api: "mbale" },
      { display: "مبارا", api: "mbale" },
    ],
  },
  TZ: {
    display: "تنزانيا",
    api: "TZ",
    cities: [
      { display: "دار السلام", api: "dar-es-salaam" },
      { display: "موسمبيقي", api: "moshi" },
      { display: "أروشا", api: "arusha" },
      { display: "مبارا", api: "mbale" },
      { display: "مبارا", api: "mbale" },
    ],
  },
  KE: {
    display: "كينيا",
    api: "KE",
    cities: [
      { display: "نيروبي", api: "nairobi" },
      { display: "مومباسا", api: "mombasa" },
      { display: "كيسومو", api: "kisumu" },
      { display: "إلدوريت", api: "eldoret" },
      { display: "ناكورو", api: "nakuru" },
      { display: "مومباسا", api: "mombasa" },
      { display: "كيسومو", api: "kisumu" },
      { display: "إلدوريت", api: "eldoret" },
      { display: "ناكورو", api: "nakuru" },
    ],
  },
  NG: {
    display: "نيجيريا",
    api: "NG",
    cities: [
      { display: "لاغوس", api: "lagos" },
      { display: "كانو", api: "kano" },
      { display: "إيبادان", api: "ibadan" },
      { display: "أبوجا", api: "abuja" },
      { display: "بنين سيتي", api: "benin-city" },
      { display: "بورت هاركورت", api: "port-harcourt" },
      { display: "مايدوغوري", api: "maiduguri" },
      { display: "جوس", api: "jos" },
      { display: "أواري", api: "owerri" },
      { display: "أواري", api: "owerri" },
    ],
  },
  GH: {
    display: "غانا",
    api: "GH",
    cities: [
      { display: "أكرا", api: "accra" },
      { display: "كوماسي", api: "kumasi" },
      { display: "تامالي", api: "tamale" },
      { display: "تامالي", api: "tamale" },
    ],
  },
  CI: {
    display: "ساحل العاج",
    api: "CI",
    cities: [
      { display: "أبيدجان", api: "abidjan" },
      { display: "ياموسوكرو", api: "yamoussoukro" },
      { display: "بواكيه", api: "bouake" },
      { display: "دالوا", api: "daloa" },
      { display: "سان بيدرو", api: "san-pedro" },
      { display: "ديمبوكرو", api: "daloa" },
      { display: "سان بيدرو", api: "san-pedro" },
      { display: "ديمبوكرو", api: "daloa" },
    ],
  },
  SN: {
    display: "السنغال",
    api: "SN",
    cities: [
      { display: "دكار", api: "dakar" },
      { display: "تيسيت", api: "thies" },
      { display: "كاولاك", api: "kaolack" },
      { display: "زيغينشور", api: "ziguinchor" },
      { display: "سانت لويس", api: "saint-louis" },
      { display: "زيغينشور", api: "ziguinchor" },
      { display: "سانت لويس", api: "saint-louis" },
    ],
  },
  GN: {
    display: "غينيا",
    api: "GN",
    cities: [
      { display: "كوناكري", api: "conakry" },
      { display: "نزيري", api: "nzerekore" },
      { display: "كانكان", api: "kankan" },
      { display: "لابيس", api: "labe" },
      { display: "كانكان", api: "kankan" },
      { display: "لابيس", api: "labe" },
    ],
  },
  ML: {
    display: "مالي",
    api: "ML",
    cities: [
      { display: "باماكو", api: "bamako" },
      { display: "سيكاسو", api: "sikasso" },
      { display: "كيتا", api: "kita" },
      { display: "سيغو", api: "segou" },
      { display: "مبور", api: "mopti" },
      { display: "كيتا", api: "kita" },
      { display: "سيغو", api: "segou" },
      { display: "مبور", api: "mopti" },
    ],
  },
  BF: {
    display: "بوركينا فاسو",
    api: "BF",
    cities: [
      { display: "واغادوغو", api: "ouagadougou" },
      { display: "بوبوديولاسو", api: "bobodioulasso" },
      { display: "كوديوغو", api: "koudougou" },
      { display: "بوبوديولاسو", api: "bobodioulasso" },
      { display: "كوديوغو", api: "koudougou" },
    ],
  },
  NE: {
    display: "النيجر",
    api: "NE",
    cities: [
      { display: "نيامي", api: "niamey" },
      { display: "زندر", api: "zinder" },
      { display: "مرادا", api: "maradi" },
      { display: "أغاديز", api: "agadez" },
      { display: "تاهوا", api: "tahoua" },
      { display: "أغاديز", api: "agadez" },
      { display: "تاهوا", api: "tahoua" },
    ],
  },
  TG: {
    display: "توغو",
    api: "TG",
    cities: [
      { display: "لومي", api: "lome" },
      { display: "سوكودالي", api: "sokode" },
      { display: "كارا", api: "kara" },
      { display: "باسار", api: "bassar" },
      { display: "أتاكبامي", api: "atakpame" },
      { display: "كارا", api: "kara" },
      { display: "باسار", api: "bassar" },
      { display: "أتاكبامي", api: "atakpame" },
    ],
  },
  SL: {
    display: "سيراليون",
    api: "SL",
    cities: [
      { display: "فريتاون", api: "freetown" },
      { display: "بو", api: "bo" },
      { display: "كينما", api: "kenema" },
      { display: "مبونت", api: "makeni" },
      { display: "كينما", api: "kenema" },
      { display: "مبونت", api: "makeni" },
    ],
  },
  LR: {
    display: "ليبيريا",
    api: "LR",
    cities: [
      { display: "مونروفيا", api: "monrovia" },
      { display: "جراند بيساو", api: "grand-bassa" },
      { display: "لوفا", api: "lofa" },
      { display: "بومبا", api: "bomi" },
      { display: "مارغيبي", api: "margibi" },
      { display: "بومبا", api: "bomi" },
      { display: "مارغيبي", api: "margibi" },
    ],
  },
  IN: {
    display: "الهند",
    api: "IN",
    cities: [
      { display: "مومباي", api: "mumbai" },
      { display: "دلهي", api: "delhi" },
      { display: "بنغالور", api: "bangalore" },
      { display: "كولكاتا", api: "kolkata" },
      { display: "تشيناي", api: "chennai" },
      { display: "أحمد آباد", api: "ahmedabad" },
      { display: "هيدراباد", api: "hyderabad" },
      { display: "بنغالور", api: "bangalore" },
      { display: "كولكاتا", api: "kolkata" },
      { display: "تشيناي", api: "chennai" },
      { display: "أحمد آباد", api: "ahmedabad" },
      { display: "هيدراباد", api: "hyderabad" },
    ],
  },
  BD: {
    display: "بنغلاديش",
    api: "BD",
    cities: [
      { display: "دكا", api: "dhaka" },
      { display: "شيتاغونغ", api: "chittagong" },
      { display: "خولنا", api: "khulna" },
      { display: "راجشاهي", api: "rajshahi" },
      { display: "باريشال", api: "barisal" },
      { display: "سيلهت", api: "sylhet" },
      { display: "راجشاهي", api: "rajshahi" },
      { display: "باريشال", api: "barisal" },
      { display: "سيلهت", api: "sylhet" },
    ],
  },
  SD: {
    display: "السودان",
    api: "SD",
    cities: [
      { display: "الخرطوم", api: "khartoum" },
      { display: "أم درمان", api: "omdurman" },
      { display: "بحري", api: "bahri" },
      { display: "بحري", api: "bahri" },
    ],
  },
  SS: {
    display: "جنوب السودان",
    api: "SS",
    cities: [
      { display: "جوبا", api: "juba" },
      { display: "واو", api: "wau" },
      { display: "مالكال", api: "malakal" },
      { display: "بور", api: "bor" },
      { display: "يي", api: "yambio" },
      { display: "بور", api: "bor" },
      { display: "يي", api: "yambio" },
    ],
  },
  ET: {
    display: "إثيوبيا",
    api: "ET",
    cities: [
      { display: "أديس أبابا", api: "addis-ababa" },
      { display: "درة دوا", api: "dire-dawa" },
      { display: "ميكيلي", api: "mikelle" },
      { display: "جيجيجا", api: "gigiga" },
      { display: "جيجيجا", api: "gigiga" },
    ],
  },
  ER: {
    display: "إريتريا",
    api: "ER",
    cities: [
      { display: "أسمرة", api: "asmara" },
      { display: "كيرنا", api: "keren" },
      { display: "مصوع", api: "massawa" },
      { display: "أسمرة", api: "asmara" },
      { display: "كيرنا", api: "keren" },
      { display: "مصوع", api: "massawa" },
    ],
  },
  DJ: {
    display: "جيبوتي",
    api: "DJ",
    cities: [
      { display: "جيبوتي", api: "djibouti" },
      { display: "أوبوك", api: "obok" },
      { display: "تادجورا", api: "tadjoura" },
      { display: "أوبوك", api: "obok" },
      { display: "تادجورا", api: "tadjoura" },
    ],
  },
  SO: {
    display: "الصومال",
    api: "SO",
    cities: [
      { display: "مقديشو", api: "mogadishu" },
      { display: "هرجيسا", api: "hargeisa" },
      { display: "بوساسو", api: "bosaso" },
      { display: "بورت هاركورت", api: "port-harcourt" },
      { display: "بوساسو", api: "bosaso" },
    ],
  },
  MY: {
    display: "ماليزيا",
    api: "MY",
    cities: [
      { display: "كوالالمبور", api: "kuala-lumpur" },
      { display: "جورج تاون", api: "george-town" },
      { display: "إبوه", api: "ipoh" },
      { display: "كوالالمبور", api: "kuala-lumpur" },
      { display: "جورج تاون", api: "george-town" },
      { display: "إبوه", api: "ipoh" },
    ],
  },
  AU: {
    display: "أستراليا",
    api: "AU",
    cities: [
      { display: "سيدني", api: "sydney" },
      { display: "ملبورن", api: "melbourne" },
      { display: "برزبن", api: "brisbane" },
      { display: "برزبن", api: "brisbane" },
    ],
  },
  NZ: {
    display: "نيوزيلندا",
    api: "NZ",
    cities: [
      { display: "أوكلاند", api: "auckland" },
      { display: "ويلينغتون", api: "wellington" },
      { display: "كرايستشيرش", api: "christchurch" },
      { display: "هاميلتون", api: "hamilton" },
      { display: "تاورانجا", api: "tauranga" },
      { display: "دنيدن", api: "dunedin" },
      { display: "نيلسون", api: "nelson" },
      { display: "روتوروا", api: "rotorua" },
      { display: "وانغانوي", api: "wanaka" },
      { display: "نيلسون", api: "nelson" },
      { display: "روتوروا", api: "rotorua" },
      { display: "وانغانوي", api: "wanaka" },
    ],
  },
  RU: {
    display: "روسيا",
    api: "RU",
    cities: [
      { display: "موسكو", api: "moscow" },
      { display: "سانت بطرسبرغ", api: "saint-petersburg" },
      { display: "نوفوسيبيرسك", api: "novosibirsk" },
      { display: "يكاترينبورغ", api: "yekaterinburg" },
      { display: "نيجني نوفغورود", api: "nizhny-novgorod" },
      { display: "كازان", api: "kazan" },
      { display: "تشيليابينسك", api: "chelyabinsk" },
      { display: "أومسك", api: "omsk" },
      { display: "سمارا", api: "samara" },
      { display: "ريازان", api: "ryazan" },
      { display: "أوليانوفسك", api: "ulyanovsk" },
      { display: "فلاديكافكاز", api: "vladikavkaz" },
      { display: "موسكو", api: "moscow" },
      { display: "سانت بطرسبرغ", api: "saint-petersburg" },
      { display: "نوفوسيبيرسك", api: "novosibirsk" },
      { display: "يكاترينبورغ", api: "yekaterinburg" },
      { display: "نيجني نوفغورود", api: "nizhny-novgorod" },
      { display: "كازان", api: "kazan" },
      { display: "تشيليابينسك", api: "chelyabinsk" },
      { display: "أومسك", api: "omsk" },
      { display: "سمارا", api: "samara" },
      { display: "ريازان", api: "ryazan" },
      { display: "أوليانوفسك", api: "ulyanovsk" },
      { display: "فلاديكافكاز", api: "vladikavkaz" },
    ],
  },
  KZ: {
    display: "كازاخستان",
    api: "KZ",
    cities: [
      { display: "نور سلطان", api: "nur-sultan" },
      { display: "ألماتي", api: "almaty" },
      { display: "شيمكنت", api: "shymkent" },
      { display: "كراغندي", api: "karaganda" },
      { display: "أكتوبي", api: "aktobe" },
      { display: "تشيمكنت", api: "shymkent" },
      { display: "كراغندي", api: "karaganda" },
      { display: "أكتوبي", api: "aktobe" },
    ],
  },
  CD: {
    display: "الكونغو",
    api: "CD",
    cities: [
      { display: "كينشاسا", api: "kinshasa" },
      { display: "لوبومباشي", api: "lubumbashi" },
      { display: "مبوجي ماي", api: "mbuji-mayi" },
      { display: "كيسانغاني", api: "kisangani" },
      { display: "كيسانغاني", api: "kisangani" },
    ],
  },
  AZ: {
    display: "أذربيجان",
    api: "AZ",
    cities: [
      { display: "باكو", api: "baku" },
      { display: "غنجة", api: "ganja" },
      { display: "سمخال", api: "sumqayit" },
      { display: "مينغيتشيفير", api: "mingachevir" },
      { display: "لنكران", api: "lenkaran" },
      { display: "شكي", api: "sheki" },
      { display: "مينغيتشيفير", api: "mingachevir" },
      { display: "لنكران", api: "lenkaran" },
      { display: "شكي", api: "sheki" },
    ],
  },
  GE: {
    display: "جورجيا",
    api: "GE",
    cities: [
      { display: "تبليسي", api: "tbilisi" },
      { display: "كوتايسي", api: "kutaisi" },
      { display: "باتومي", api: "batumi" },
      { display: "زغديدي", api: "zgudidi" },
      { display: "باتومي", api: "batumi" },
      { display: "زغديدي", api: "zgudidi" },
    ],
  },
  AM: {
    display: "أرمينيا",
    api: "AM",
    cities: [
      { display: "يريفان", api: "yerevan" },
      { display: "غيومري", api: "gyumri" },
      { display: "فانادزور", api: "vanadzor" },
      { display: "فانادزور", api: "vanadzor" },
    ],
  },
  TD: {
    display: "تشاد",
    api: "TD",
    cities: [
      { display: "نجامينا", api: "n-djamena" },
      { display: "موندو", api: "moundou" },
      { display: "ساره", api: "sare" },
      { display: "أبيشي", api: "abeche" },
      { display: "أبيشي", api: "abeche" },
    ],
  },
  CM: {
    display: "الكاميرون",
    api: "CM",
    cities: [
      { display: "ياوندي", api: "yaounde" },
      { display: "دوالا", api: "douala" },
      { display: "غاروا", api: "garoua" },
      { display: "بامندا", api: "bamenda" },
      { display: "ماروا", api: "maroua" },
      { display: "بامندا", api: "bamenda" },
      { display: "ماروا", api: "maroua" },
    ],
  },
  CN: {
    display: "الصين",
    api: "CN",
    cities: [
      { display: "بكين", api: "beijing" },
      { display: "شانغهاي", api: "shanghai" },
      { display: "تيانجين", api: "tianjin" },
      { display: "شيان", api: "xian" },
      { display: "شينزين", api: "shenzhen" },
      { display: "قوانغجو", api: "guangzhou" },
      { display: "شينزين", api: "shenzhen" },
      { display: "قوانغجو", api: "guangzhou" },
    ],
  },
  MZ: {
    display: "موزمبيق",
    api: "MZ",
    cities: [
      { display: "مابوتو", api: "maputo" },
      { display: "ماتولا", api: "matola" },
      { display: "بيرا", api: "beira" },
      { display: "نامبيا", api: "nampula" },
      { display: "ماتولا", api: "matola" },
      { display: "بيرا", api: "beira" },
      { display: "نامبيا", api: "nampula" },
    ],
  },
  ZA: {
    display: "جنوب أفريقيا",
    api: "ZA",
    cities: [
      { display: "جوهانسبرغ", api: "johannesburg" },
      { display: "كيب تاون", api: "cape-town" },
      { display: "دوربان", api: "durban" },
      { display: "بريتوريا", api: "pretoria" },
      { display: "بلومفونتين", api: "bloemfontein" },
      { display: "بلومفونتين", api: "bloemfontein" },
    ],
  },
  ZM: {
    display: "زامبيا",
    api: "ZM",
    cities: [
      { display: "لوساكا", api: "lusaka" },
      { display: "كيتوي", api: "kitwe" },
      { display: "ندولا", api: "ndola" },
      { display: "كابوي", api: "kabwe" },
      { display: "مونزا", api: "monze" },
      { display: "ندولا", api: "ndola" },
      { display: "كابوي", api: "kabwe" },
      { display: "مونزا", api: "monze" },
    ],
  },
  ZW: {
    display: "زيمبابوي",
    api: "ZW",
    cities: [
      { display: "هراري", api: "harare" },
      { display: "بولاوايو", api: "bulawayo" },
      { display: "شيتوي", api: "chitungwiza" },
      { display: "موتارا", api: "mutare" },
      { display: "جوينو", api: "gweru" },
      { display: "موتارا", api: "mutare" },
      { display: "جوينو", api: "gweru" },
    ],
  },
  FR: {
    display: "فرنسا",
    api: "FR",
    cities: [
      { display: "باريس", api: "paris" },
      { display: "مارسيليا", api: "marseille" },
      { display: "ليون", api: "lyon" },
      { display: "تولوز", api: "toulouse" },
      { display: "نيس", api: "nice" },
      { display: "نانت", api: "nantes" },
      { display: "ستراسبورغ", api: "strasbourg" },
      { display: "مونبيلييه", api: "montpellier" },
      { display: "بوردو", api: "bordeaux" },
      { display: "ليل", api: "lille" },
      { display: "رين", api: "rennes" },
      { display: "ريمس", api: "reims" },
      { display: "ليموج", api: "limoges" },
      { display: "أنجيه", api: "angers" },
      { display: "بيسيه", api: "besancon" },
      { display: "كليرمون فيراند", api: "clermont-ferrand" },
      { display: "تروا", api: "troyes" },
      { display: "أفينيون", api: "avignon" },
      { display: "بيزييه", api: "bayonne" },
      { display: "بيزييه", api: "bayonne" },
    ],
  },
  PH: {
    display: "الفلبين",
    api: "PH",
    cities: [
      { display: "مانيلا", api: "manila" },
      { display: "كيزون سيتي", api: "quezon-city" },
      { display: "دافاو", api: "davao" },
      { display: "كالوكان", api: "caloocan" },
      { display: "سيبو", api: "cebu" },
      { display: "زامبوانجا", api: "zamboanga" },
      { display: "أنتيبولو", api: "antipolo" },
      { display: "باكولود", api: "bacolod" },
      { display: "بيهولو", api: "beyrouth" },
      { display: "بيهولو", api: "beyrouth" },
    ],
  },
  DE: {
    display: "ألمانيا",
    api: "DE",
    cities: [
      { display: "برلين", api: "berlin" },
      { display: "هامبورغ", api: "hamburg" },
      { display: "ميونخ", api: "munich" },
      { display: "كولونيا", api: "cologne" },
      { display: "فرانكفورت", api: "frankfurt" },
      { display: "شتوتغارت", api: "stuttgart" },
      { display: "دوسلدورف", api: "dusseldorf" },
      { display: "دورتموند", api: "dortmund" },
      { display: "إسن", api: "essen" },
      { display: "ليبزيغ", api: "leipzig" },
      { display: "برمن", api: "bremen" },
      { display: "دريسدن", api: "dresden" },
      { display: "هانوفر", api: "hanover" },
      { display: "نورنبرغ", api: "nuremberg" },
      { display: "دويسبورغ", api: "duisburg" },
      { display: "بوخوم", api: "bochum" },
      { display: "وبوبن", api: "wuppertal" },
      { display: "بيلفيلد", api: "bielefeld" },
      { display: "بون", api: "bonn" },
      { display: "مونستر", api: "munster" },
      { display: "كارلسروه", api: "karlsruhe" },
      { display: "مانهايم", api: "mannheim" },
      { display: "أوغسبورغ", api: "augsburg" },
      { display: "ويزبادن", api: "wiesbaden" },
      { display: "مونشنغلادباخ", api: "monchengladbach" },
      { display: "كيل", api: "kiel" },
      { display: "إرفورت", api: "erfurt" },
      { display: "ماغدبورغ", api: "magdeburg" },
      { display: "فولفسبورغ", api: "wolfsburg" },
      { display: "أولم", api: "ulm" },
      { display: "هايلبرون", api: "heilbronn" },
      { display: "بوتسدام", api: "potsdam" },
      { display: "ريجنسبورغ", api: "regensburg" },
      { display: "إيمدين", api: "ingolstadt" },
      { display: "فورتسبورغ", api: "furth" },
      { display: "روستوك", api: "rostock" },
      { display: "ماينتس", api: "mainz" },
      { display: "كوتبوس", api: "cottbus" },
      { display: "جينا", api: "jena" },
    ],
  },
  IT: {
    display: "إيطاليا",
    api: "IT",
    cities: [
      { display: "روما", api: "rome" },
      { display: "ميلانو", api: "milan" },
      { display: "نابولي", api: "naples" },
      { display: "تورينو", api: "turin" },
      { display: "باليرمو", api: "palermo" },
      { display: "جينوا", api: "genoa" },
      { display: "فلورنسا", api: "florence" },
      { display: "بولونيا", api: "bologna" },
      { display: "بولونيا", api: "bologna" },
    ],
  },
  MR: {
    display: "موريتانيا",
    api: "MR",
    cities: [{ display: "نواكشوط", api: "nouakchott" }],
  },
  MW: {
    display: "مالاوي",
    api: "MW",
    cities: [
      { display: "ليلونغوي", api: "lilongwe" },
      { display: "بلانتير", api: "blantyre" },
      { display: "مزوزو", api: "mzuzu" },
      { display: "زومبا", api: "zomba" },
      { display: "مزوزو", api: "mzuzu" },
      { display: "زومبا", api: "zomba" },
    ],
  },
  TH: {
    display: "تايلاند",
    api: "TH",
    cities: [
      { display: "بانكوك", api: "bangkok" },
      { display: "نونثابوري", api: "nonthaburi" },
      { display: "نونثابوري", api: "nonthaburi" },
    ],
  },
  US: {
    display: "الولايات المتحدة",
    api: "US",
    cities: [
      { display: "نيويورك", api: "new-york" },
      { display: "لوس أنجلوس", api: "los-angeles" },
      { display: "شيكاغو", api: "chicago" },
      { display: "هيوستن", api: "houston" },
      { display: "فيلادلفيا", api: "philadelphia" },
      { display: "فينيكس", api: "phoenix" },
      { display: "سان أنطونيو", api: "san-antonio" },
      { display: "سان دييغو", api: "san-diego" },
      { display: "دالاس", api: "dallas" },
      { display: "سان خوسيه", api: "san-jose" },
      { display: "أوستن", api: "austin" },
      { display: "جاكسونفيل", api: "jacksonville" },
      { display: "فورت وورث", api: "fort-worth" },
      { display: "كولومبوس", api: "columbus" },
      { display: "سان فرانسيسكو", api: "san-francisco" },
      { display: "شارلوت", api: "charlotte" },
      { display: "إنديانابوليس", api: "indianapolis" },
      { display: "سياتل", api: "seattle" },
      { display: "دنفر", api: "denver" },
      { display: "واشنطن", api: "washington" },
      { display: "بوسطن", api: "boston" },
      { display: "إل باسو", api: "el-paso" },
      { display: "ناشفيل", api: "nashville" },
      { display: "ديترويت", api: "detroit" },
    ],
  },
  BJ: {
    display: "بنين",
    api: "BJ",
    cities: [
      { display: "بورتو نوفو", api: "porto-novo" },
      { display: "كوتونو", api: "cotonou" },
    ],
  },
  MG: {
    display: "مدغشقر",
    api: "MG",
    cities: [
      { display: "أنتاناناريفو", api: "antananarivo" },
      { display: "تواماسينا", api: "toamasina" },
      { display: "فيانارانتسوا", api: "fianarantsoa" },
      { display: "ماهاجانجا", api: "mahajanga" },
      { display: "توليارا", api: "toliara" },
      { display: "أنتسيرانانا", api: "antsiranana" },
      { display: "ماهاجانجا", api: "mahajanga" },
      { display: "توليارا", api: "toliara" },
      { display: "أنتسيرانانا", api: "antsiranana" },
    ],
  },
  CF: {
    display: "جمهورية أفريقيا الوسطى",
    api: "CF",
    cities: [{ display: "بانغي", api: "bangui" }],
  },
  MM: {
    display: "ميانمار",
    api: "MM",
    cities: [
      { display: "نايبيداو", api: "naypyidaw" },
      { display: "يانغون", api: "yangon" },
      { display: "ماندالاي", api: "mandalay" },
      { display: "تاونغجو", api: "taunggyi" },
      { display: "ماجوي", api: "magway" },
    ],
  },
  GM: {
    display: "غامبيا",
    api: "GM",
    cities: [{ display: "بانجول", api: "banjul" }],
  },
  GB: {
    display: "المملكة المتحدة",
    api: "GB",
    cities: [
      { display: "لندن", api: "london" },
      { display: "برمنغهام", api: "birmingham" },
      { display: "ليدز", api: "leeds" },
      { display: "غلاسكو", api: "glasgow" },
      { display: "شيفيلد", api: "sheffield" },
      { display: "مانشستر", api: "manchester" },
      { display: "برادفورد", api: "bradford" },
      { display: "ليفربول", api: "liverpool" },
      { display: "إدنبرة", api: "edinburgh" },
    ],
  },
  LK: {
    display: "سريلانكا",
    api: "LK",
    cities: [
      { display: "كولومبو", api: "colombo" },
      { display: "ديغومويا", api: "dehiwala-mount-lavinia" },
      { display: "موراتوا", api: "moratuwa" },
      { display: "جافنا", api: "jaffna" },
      { display: "نيغومبو", api: "negombo" },
      { display: "بيرادينيا", api: "beruwala" },
    ],
  },
  BA: {
    display: "البوسنة والهرسك",
    api: "BA",
    cities: [
      { display: "سراييفو", api: "sarajevo" },
      { display: "بانيالوكا", api: "banja-luka" },
      { display: "توزلا", api: "tuzla" },
      { display: "زينيتسا", api: "zenica" },
      { display: "موستار", api: "mostar" },
      { display: "بريجيج", api: "brcko" },
    ],
  },
  AL: {
    display: "ألبانيا",
    api: "AL",
    cities: [
      { display: "تيرانا", api: "tirana" },
      { display: "دوريس", api: "durrës" },
      { display: "فلوري", api: "vlora" },
      { display: "شكودرا", api: "shkoder" },
      { display: "الباسان", api: "elbasan" },
      { display: "فيرو", api: "fier" },
      { display: "كورتش", api: "korçë" },
      { display: "بريشتينا", api: "pristina" },
    ],
  },
  CA: {
    display: "كندا",
    api: "CA",
    cities: [
      { display: "تورونتو", api: "toronto" },
      { display: "مونتريال", api: "montreal" },
      { display: "كالغاري", api: "calgary" },
      { display: "أوتاوا", api: "ottawa" },
      { display: "إدمونتون", api: "edmonton" },
      { display: "ميسيسوجا", api: "mississauga" },
      { display: "فانكوفر", api: "vancouver" },
      { display: "هاميلتون", api: "hamilton" },
      { display: "كويبك", api: "quebec" },
      { display: "وينيبيغ", api: "winnipeg" },
      { display: "كيبيك", api: "quebec" },
      { display: "وينيبيغ", api: "winnipeg" },
    ],
  },
  NP: {
    display: "نيبال",
    api: "NP",
    cities: [
      { display: "كاتماندو", api: "kathmandu" },
      { display: "بوكهارا", api: "biratnagar" },
    ],
  },
  BI: {
    display: "بوروندي",
    api: "BI",
    cities: [{ display: "بوجومبورا", api: "bujumbura" }],
  },
  ES: {
    display: "إسبانيا",
    api: "ES",
    cities: [
      { display: "مدريد", api: "madrid" },
      { display: "برشلونة", api: "barcelona" },
      { display: "فالنسيا", api: "valencia" },
      { display: "سرقسطة", api: "zaragoza" },
      { display: "إشبيلية", api: "seville" },
      { display: "مالقة", api: "malaga" },
      { display: "مورسيا", api: "murcia" },
      { display: "بلباو", api: "bilbao" },
      { display: "لاس بالماس", api: "las-palmas" },
    ],
  },
  SG: {
    display: "سنغافورة",
    api: "SG",
    cities: [{ display: "سنغافورة", api: "singapore" }],
  },
};

const countriesArray = Object.entries(countries).sort((a, b) =>
  a[1].display.localeCompare(b[1].display)
);
const sortedCountries = Object.fromEntries(countriesArray);
export default sortedCountries;
